# Generated by Django 3.1.7 on 2021-03-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgeassembly', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly',
            name='assembly_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
