# Generated by Django 3.1.7 on 2021-03-18 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cgeassembly', '0002_assembly_assembly_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='InFavor',
            fields=[
                ('choice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cgeassembly.choice')),
            ],
            bases=('cgeassembly.choice',),
        ),
        migrations.AlterModelOptions(
            name='assembly',
            options={'verbose_name_plural': 'Assemblies'},
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(choices=[('A', 'abstenido'), ('F', 'a favor'), ('C', 'en contra')], max_length=200),
        ),
        migrations.AlterField(
            model_name='motion',
            name='current_motion',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='motion',
            name='open_to_vote',
            field=models.IntegerField(default=0),
        ),
    ]
