# Generated by Django 3.1.7 on 2021-03-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgeassembly', '0003_auto_20210318_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='choice',
            name='votes',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.DeleteModel(
            name='InFavor',
        ),
    ]
