# Generated by Django 3.1.7 on 2021-03-18 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cgeassembly', '0004_auto_20210318_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='motion',
            name='assembly',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cgeassembly.assembly'),
        ),
    ]
