# Generated by Django 3.1.7 on 2021-03-18 19:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cgeassembly', '0005_motion_assembly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assembly',
            name='agenda',
            field=models.CharField(default='Placeholder', max_length=500),
        ),
        migrations.AlterField(
            model_name='assembly',
            name='quorum',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(choices=[('a favor', 'a favor'), ('abstenido', 'abstenido'), ('en contra', 'en contra')], max_length=200),
        ),
        migrations.AlterField(
            model_name='motion',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 18, 19, 23, 0, 341547, tzinfo=utc), verbose_name='date published'),
        ),
    ]
