# Generated by Django 3.1.7 on 2021-03-18 19:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cgeassembly', '0006_auto_20210318_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(choices=[('a favor', 'a favor'), ('en contra', 'en contra'), ('abstenido', 'abstenido')], max_length=200),
        ),
        migrations.AlterField(
            model_name='motion',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
    ]
