# Generated by Django 3.1.7 on 2021-03-18 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cgeassembly', '0007_auto_20210318_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(choices=[('abstenido', 'abstenido'), ('a favor', 'a favor'), ('en contra', 'en contra')], max_length=200),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('faculty', models.CharField(choices=[('ingenieria', 'ingeniería'), ('humanidades', 'humanidades'), ('biologia', 'biología')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
