# Generated by Django 3.1.7 on 2021-03-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgeassembly', '0008_auto_20210318_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(choices=[('abstenido', 'abstenido'), ('en contra', 'en contra'), ('a favor', 'a favor')], max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='faculty',
            field=models.CharField(choices=[('biologia', 'biología'), ('humanidades', 'humanidades'), ('ingenieria', 'ingeniería')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(default=0),
        ),
    ]
